name: ARC Pro A/V
favicon: null
layout_spectrum: 0.06323549500666559
typography_spectrum: 0.6943755145184696
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.17586256633512676
  lightness: 0.6385129224509001
  saturation: 0.4331495463848114
  rhythmicContrast: 0.8719122214242816
purpose: []
