name: ARC Pro Audio Visual
favicon: null
layout_spectrum: 0.88618
typography_spectrum: 0.56791
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#0089ff'
    - '#00f4fe'
    - '#b15300'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
